approach:
  name: TripletLoss
  params:
    metric: cosine    # embeddings are optimized for cosine metric
    clamp: positive   # triplet loss variant
    margin: 0.2       # triplet loss margin
    duration: 2       # sequence duration
    sampling: all     # triplet sampling strategy
    per_fold: 40      # number of speakers per fold
    per_label: 3      # number of sequences per speaker

feature_extraction:
  name: LibrosaSpectrogram

feature_normalization:
  name: GlobalStandardization

architecture:
  name: VGGVox

scheduler:
  name: CyclicScheduler
  params:
      learning_rate: auto
